### ISSUE TITLE
Challenge3 - Complete System Level Architecture 

### ISSUE THREAD

**Issue by muneebullashariff** [muneeb-mbytes/UVMF#10]
### **Problem Statement:**

![6F55F6AC-8671-4E49-BC0F-1E2468B086A4](https://user-images.githubusercontent.com/15922511/209420940-7d739f79-1174-4234-ba9f-430fc1f346bd.jpeg)

**Comment by muneebullashariff** [comment]
### Tasks to be completed:

- [x] Create separate branch name for the challenge 

- [x] Block level testbench for block1 (successful compilation)
- [x] Block level testbench for block2 (successful compilation)
- [x] Block level testbench for block3 (successful compilation)

- [x] Subsytem level testbench, by REUSING block level Environments, for below diagram: (successful compilation)
![4D8EBA01-74E0-4B91-8297-006BC13A48C7](https://user-images.githubusercontent.com/15922511/209421121-dcf9a21a-482a-4b4f-ab54-732ca95555ff.jpeg)

- [ ] System level testbench, by REUSING, subsytem level ENV and block level ENV, for below diagram: (successful compilation)

![30691B84-C68D-45F1-9C83-D7A0AEFC2217](https://user-images.githubusercontent.com/15922511/209421387-c735c040-91ae-4636-94ea-e12e91653628.jpeg)

- [ ] Have a successful commit for each task mentioned 
- [ ] Have a final PR for the challenge

**Comment by muneebullashariff** [comment]
![16AAF377-5E8B-4CA4-8E3B-724BF19367F7](https://user-images.githubusercontent.com/15922511/209421545-d9f26da8-efa5-4059-8947-31b69f925acb.jpeg)

**Comment by muneebullashariff** [comment]
![F5B79B11-A39D-46F3-A60B-3C007018F9D2](https://user-images.githubusercontent.com/15922511/209421660-67c208d3-dc20-4fd1-a362-6dfea4d611c0.jpeg)

**Comment by muneebullashariff** [comment]
![19218857-5AD4-4304-ACEA-D70C74F0153E](https://user-images.githubusercontent.com/15922511/209421677-bc4b2982-e439-4987-ad76-6c6c6c279822.jpeg)
